import "~/styles/globals.css";
import { Roboto } from "next/font/google";
import Header from "./_components/header";
import Footer from "./_components/footer";
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en " className={roboto.className}>
      <body>
        <TRPCReactProvider>
          <Header />
          {children}
          <Footer />
        </TRPCReactProvider>
      </body>
    </html>
  );
}

// className={`${GeistSans.variable}`}
